cart/urls.py
from django.urls import path
from .views import cart_view, add_to_cart, update_cart, remove_from_cart, apply_discount, clear_cart ,checkout, checkout_view
from .favourite import add_favourite, remove_favourite, clear_favourite
from .comparison import comparison_view ,add_comparison, clear_comparison


urlpatterns = [
    path('', cart_view, name='cart'),
    path('add', add_to_cart, name='add_to_cart' ),
    path('update', update_cart, name='update_cart' ),
    path('remove', remove_from_cart, name='remove_cart' ),
    path('discount', apply_discount, name='discount_apply' ),
    path('clear', clear_cart, name='clear_cart' ),
    path('Get_checkout', checkout, name='get_checkout' ),
    path('checkout', checkout_view, name='checkout' ),
    path('comparison', comparison_view, name="comparison"),
    path('comparison/add', add_comparison, name="add_comparison"),
    path('comparison/clear', clear_comparison, name="clear_comparison"),
    path('favourite/add', add_favourite, name="add_favourite"),
    path('favourite/remove', remove_favourite, name="remove_favourite"),
    path('favourite/clear', clear_favourite, name="clear_favourite"),
]

monitor/urls.py
from django.urls import path
from .views import index


urlpatterns = [
    path('', index, name='monitor'),
]

root/urls.py
"""
2020 Black
root URL configuration
developer : #ABS
"""

# Import all requirements
from cart.views import CartViewSet, support_index, support_room, support_add, SupportViewSet
from .local_settings import DEVELOPERS_PANEL, ADMINS_PANEL, SITE_API, SITE_TRAFFIC
from cart.support import post_message, get_message, close_room
from product.views import price_search, last_offers, submit_order, get_bank
from wagtail.documents import urls as wagtaildocs_urls
from django.conf.urls import handler404, handler500
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.contrib.sitemaps.views import sitemap
from django.views.generic.base import RedirectView
from django.urls import include, path, re_path
from django.conf.urls.static import static
from index.views import custom_pages_view
from wagtail import urls as wagtail_urls
from rest_framework import routers
from django.contrib import admin
from django.conf import settings
from .api import api_router
import os.path


# NOTE : PLEASE KEEP THIS FILE SAFE !
urlpatterns = [
    path('api/support/', SupportViewSet.as_view(), name='support-api'),
    path('support/post_message', post_message, name='post_message'),
    path('support/get_message', get_message, name='get_message'),
    path('category/', include('category.urls'), name="category"),
    path('page/<Page>/',custom_pages_view, name="custom_page"),
    path("support/<room>/", support_room, name="Support_room"),
    path('api/cart/', CartViewSet.as_view(), name='cart-api'),
    path("summernote/", include("django_summernote.urls")),
    path('priceSearch', price_search, name="priceSearch"),
    path('last_offers/', last_offers, name="last_offers"),
    path('support/close', close_room, name='close_room'),
    path('support/add',support_add, name="Support_add"),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('user_accounts.urls')),
    path('UsersAccounts/', include('allauth.urls')),
    path(ADMINS_PANEL, include(wagtailadmin_urls)),
    path('UNIQUEDOC/', include(wagtaildocs_urls)),
    path('get_order/', submit_order, name="order"),
    path(SITE_TRAFFIC, include("monitor.urls")),
    path(DEVELOPERS_PANEL, admin.site.urls),
    path('get_bank/', get_bank, name="bank"),
    path('cart/', include('cart.urls')),
    path(SITE_API, api_router.urls),
    
    re_path(r'^sitemap.xml$', sitemap),
    re_path(r'^info/', include('monitor.info'), name='info'),
    re_path(r'', include(wagtail_urls)),
]

# Custom static & storage files configuration
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL + 'images/', document_root=os.path.join(settings.MEDIA_ROOT, 'images'))

urlpatterns += [
    path('favicon.ico', RedirectView.as_view(url=settings.STATIC_URL + 'img/favicon.ico'))
]

# Add the 404-500 error view
handler404 = 'index.views.page_not_found_error'
handler500 = 'index.views.server_error'

user_accounts/forms.py
'''
Users Accounts form and fields
developer: #ABS
'''

# Import all requirements
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm, ReadOnlyPasswordHashField, AuthenticationForm
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import authenticate, login as DjangoLogin
from allauth.account.forms import SignupForm , ChangePasswordForm
from wagtail.users.forms import UserEditForm, UserCreationForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UsernameField
from django.shortcuts import render, redirect
from .utils import validate_Opassword
from .models import user_accounts
from django.db.models import Q
from django.db import models
from django import forms
  
   
# Custom User Creation Form class
class CustomUserCreationForm(forms.ModelForm):
    phoneNumber = forms.CharField(
        label='شماره تماس',
        widget=forms.TextInput(attrs={'placeholder': 'شماره تماس به همراه صفر ابتدایی مانند :‌۰۹۱۲۱۲۳۴۵۶۷'})
    )
    password1 = forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={'placeholder': 'رمز عبور'})
    )
    password2 = forms.CharField(
        label='تکرار رمز عبور',
        widget=forms.PasswordInput(attrs={'placeholder': 'تکرار رمز عبور'})
    )

    # اضافه کردن بررسی شماره تلفن
    def clean_phoneNumber(self):
        phoneNumber = self.cleaned_data.get("phoneNumber")

        # بررسی تعداد ارقام شماره تلفن
        if len(phoneNumber) != 11:
            raise forms.ValidationError("شماره تلفن باید ۱۱ رقم باشد مانند ۰۹۱۲۱۲۳۴۵۶۷")

        return phoneNumber


    class Meta:
        model = user_accounts
        fields = ('phoneNumber', 'password1', 'password2')

    def clean_password2(self):
        # بررسی تطابق رمز عبور
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("رمز عبور وارد شده مطابقت ندارند")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()
        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = user_accounts
        fields = ['first_name', 'last_name',]


class UserEmailForm(forms.ModelForm):
    class Meta:
        model = user_accounts
        fields = ['first_name', 'last_name','email']


class change_pass_users(forms.Form):
    old_password = forms.CharField(label='رمز عبور قدیمی', widget=forms.PasswordInput)
    new_password = forms.CharField(label='رمز عبور جدید', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='تکرار رمز عبور جدید', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get('old_password')
        new_password = cleaned_data.get('new_password')

        if old_password and new_password:
            if not check_password(old_password, self.user.password):
                self.add_error('old_password', 'رمز عبور قدیمی اشتباه است.')
            elif old_password == new_password:
                self.add_error('new_password', 'رمز عبور جدید نمی‌تواند با رمز عبور قدیمی برابر باشد.')

        return cleaned_data

    def clean_confirm_password(self):
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if new_password and confirm_password and new_password != confirm_password:
            raise forms.ValidationError('رمز عبور جدید و تکرار آن باید یکسان باشند.')

        return confirm_password
        

class UserAccountsForm(forms.ModelForm):
    class Meta:
        model = user_accounts
        fields = [
            'email', 'username', 'WPOPass', 'first_name', 'last_name',
            'phoneNumber'
        ]
        widgets = {
            'date_joined': forms.DateTimeInput(attrs={'type': 'datetime-local', 'disabled': True}),
        }

# Custom User authentication Form class
class LoginForm(AuthenticationForm):
    username = UsernameField(
        label='نام کاربری',
        widget=forms.TextInput(attrs={'placeholder': 'شماره تلفن / ایمل / نام کاربری'}))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            # Check if user exists with username, email, or phone number
            try:
                user = user_accounts.objects.get(
                    Q(username=username) | Q(email=username) | Q(phoneNumber=username)
                )
            except user_accounts.DoesNotExist:
                raise forms.ValidationError('نام کاربری، ایمیل یا شماره تماس نامعتبر است')

            if user.has_new_password:
                auth = authenticate(request=self.request, username=username, password=password)
                if not auth:
                    raise forms.ValidationError('نام کاربری یا رمز عبور نامعتبر است')
                elif auth:
                    self.confirm_login_allowed(auth)
                    DjangoLogin(self.request, auth)
            else:
                WOPass = user.WPOPass
                is_valid_password = validate_Opassword(password, user.WPOPass)
                if is_valid_password:
                    user.has_new_password = True
                    new_password_hash = make_password(password, salt='PDHTwqLLv7nIsw60zr767s')
                    user.password = new_password_hash
                    user.save(update_fields=['password', 'has_new_password'])
                    user = authenticate(request=self.request, username=username, password=password)
                    self.confirm_login_allowed(user)
                    DjangoLogin(self.request, user)
                else:
                    raise forms.ValidationError('نام کاربری یا رمز عبور نامعتبر است')

            # Check if password is valid
            if not user.check_password(password):
                raise forms.ValidationError('نام کاربری یا رمز عبور نامعتبر است')

        return self.cleaned_data


# Custom User Change Form
class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(label='ایمیل')
    username = forms.CharField(label='نام کاربری')
    full_name = forms.CharField(label='نام کامل')
    phoneNumber = forms.CharField(label='شماره تماس')
    is_active = forms.BooleanField(label='فعال', required=False)
    is_staff = forms.BooleanField(label='کارمند', required=False)
    date_joined = forms.DateTimeField(label='تاریخ عضویت', widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = user_accounts
        fields = ('email', 'username', 'full_name', 'phoneNumber', 'is_active', 'is_staff', 'date_joined')

    def clean_password(self):
        return self.initial["password"]
    

# Custom User Password Change Form
class CustomPasswordChangeForm(ChangePasswordForm):
    new_password1 = forms.CharField(
        label=_("رمز عبور جدید"),
        widget=forms.PasswordInput,
        strip=False,
        required=False,
    )
    new_password2 = forms.CharField(
        label=_("تأیید رمز عبور جدید"),
        strip=False,
        widget=forms.PasswordInput,
        required=False,
    )

    class Meta:
        model = user_accounts

    def clean(self):
        cleaned_data = super().clean()

        # بررسی اینکه کاربر جدید است و نیاز به رمز عبور قوی دارد
        if self.user.has_new_password:
            new_password1 = cleaned_data.get('new_password1')
            new_password2 = cleaned_data.get('new_password2')
            if not new_password1:
                raise forms.ValidationError(
                    _("شما باید یک رمز عبور جدید وارد کنید.")
                )
            if not validate_password(new_password1):
                raise forms.ValidationError(
                    _("رمز عبور باید حداقل ۸ کاراکتر باشد و شامل حروف بزرگ، حروف کوچک و اعداد باشد.")
                )
            if new_password1 != new_password2:
                raise forms.ValidationError(
                    _("دو فیلد رمز عبور با یکدیگر مطابقت ندارند.")
                )
        else:
            # بررسی اینکه کاربر تنها باید رمز عبور فعلی را تأیید کند
            old_password = cleaned_data.get('old_password')
            if not self.user.check_password(old_password):
                raise forms.ValidationError(
                    _("رمز عبور قدیمی شما به درستی وارد نشده است. لطفاً دوباره آن را وارد کنید.")
                )

            new_password1 = cleaned_data.get('new_password1')
            new_password2 = cleaned_data.get('new_password2')
            if new_password1 or new_password2:
                raise forms.ValidationError(
                    _("شما تنها می‌توانید رمز عبور خود را تغییر دهید اگر رمز عبور فعلی خود را به درستی وارد کنید.")
                )

        return cleaned_data

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{%block TITLE%}ورود به حساب کاربری{% endblock %}
{% block CSS %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block CONTENT %}
{% if user.is_authenticated %}
<h3 style="color: red;"> Error : you are now Login ! </h3>
<button onclick="window.history.back();">Go Back</button>
<a href="{% url 'logout' %}"><button>logout</button></a>
{% else %}
    <div class="container-fluid">
      <div class="row">
        <div class="col asidelogform">
          <div class="container">
            <section class="main">
              <form class="form-3" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="checkbox" name="remember" id="remember" />
                <label for="remember">مرا به خاطر بسپار</label>
                <input
                  type="submit"
                  name="submit"
                  value="ورود به حساب کاربری"
                />
              </form>
            </section>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
{% endblock %}


templates/accounts/login_or_signup.html
{% extends 'base.html' %}
{% load static %}
{% block HEADING %}
<meta name="description" content="" />
<meta name="keywords" content="" />
{% endblock %}
{%block TITLE%}ورود به حساب کاربری{% endblock %}
{% block CSS %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/accounts/stylelogin.css' %}" />
<link rel="stylesheet" href="{% static 'css/accounts/dashboard.css' %}" />
<link rel="stylesheet" href="{% static 'css/accounts/userpanel.css' %}" />
{% endblock %}
{% block CONTENT %}
{% if user.is_authenticated %}
<h3 style="color: red;"> Error : you are now Login ! </h3>
<button onclick="window.history.back();">Go Back</button>
<a href="{% url 'logout' %}"><button>logout</button></a>
{% else %}
    <!--<div class="container-fluid">-->
    <!--  <div class="row">-->
    <!--    <div class="col asidelogform">-->
    <!--      <div class="container">-->
    <!--        <section class="main">-->
    <!--          <form class="form-3" method="POST">-->
    <!--            -->
    <!--            {{ login_form.as_p }}-->
    <!--            <input type="checkbox" name="remember" id="remember" />-->
    <!--            <label for="remember">مرا به خاطر بسپار</label>-->
    <!--            <input-->
    <!--              type="submit"-->
    <!--              name="submit"-->
    <!--              value="ورود به حساب کاربری"-->
    <!--            />-->
    <!--          </form>-->
    <!--        </section>-->
    <!--      </div>-->
    <!--      <div class="container">-->
    <!--        <section class="main">-->
    <!--          <form class="form-3" method="POST">-->
    <!--            {% csrf_token %}-->
    <!--            <label for="{{ signup_form.phoneNumber.id_for_label }}">شماره تماس</label>-->
    <!--            {{ signup_form.phoneNumber }}-->
    <!--            <label for="signup_form.password1.id_for_label">رمزعبور</label>-->
    <!--            {{ signup_form.password1 }}-->
    <!--            <label for="signup_form.password2.id_for_label">تکرار رمزعبور</label>-->
    <!--            {{ signup_form.password2 }}-->
    <!--            <input type="checkbox" name="remember" id="remember" />-->
    <!--            <label for="remember">مرا به خاطر بسپار</label>-->
    <!--            <input type="submit" name="submit" value="ساخت حساب کاربری" />-->
    <!--          </form>-->
    <!--        </section>-->
    <!--      </div>-->
    <!--    </div>-->
    <!--    <div class="col asidelogimg">-->
    <!--      <div></div>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--</div>-->
    <section class="container-fluid logsec">
    <h2 class="m-5">وارد حساب کاربری خود شوید و یا ثبت نام کنید</h2>
    <div class="container" id="container">
      <div class="form-container sign-up-container">
        <form method="POST">
            {% csrf_token %}
          <a href="#">
            <img src="http://kikpick.com/media/images/kikpick.original.png" alt="لوگو سایت فروشگاه اینترنتی کیک پیک"
              class="text-center" width="100%" /></a>
          <h3>ثبت نام در سایت</h3>

          <span> برای ثبت نام از شماره تماس استفاده کنید</span>
          <input id="id_phoneNumber" type="text" name="phoneNumber" placeholder="شماره تماس" required />
          <input id="id_password1" type="password" name="password1" placeholder="رمزعبور" required />
          <input id="id_password2" type="password" name="password2" placeholder="تکرار رمزعبور" required />
          <input class="sflog" type="submit" name="submit" value="ثبت نام" />
        </form>
      </div>
      <div class="form-container sign-in-container">
        <form method="POST">
            {% csrf_token %}
          <a href="#">
            <img src="http://kikpick.com/media/images/kikpick.original.png" alt="لوگو سایت فروشگاه اینترنتی کیک پیک"
              class="text-center" width="100%" /></a>
          <h3> ورود به حساب </h3>

          <span> برای ورود از شماره تماس استفاده کنید</span>
          <input id="id_username" type="text" name="username" placeholder="شماره تماس" autocapitalize="none"
            autocomplete="username" maxlength="20" required />
          <input id="id_password" type="password" name="password" placeholder="رمزعبور"
            autocomplete="current-password required " />
          <a href="#"><span class="black-color">رمزعبور را فراموش کردید؟</span> <u>کلیک کنید</u></a>
          <input class="sflog" type="submit" name="submit" value="ورود" />
        </form>
      </div>
      <div class="overlay-container">
        <div class="overlay">
          <div class="overlay-panel overlay-left">
            <h3>!سلام دوست عزیز</h3>
            <p>
              جهت ثبت نام در سایت کیک پیک لطفا از شماره تماس خود استفاده کنید
            </p>
            <button class="ghost" id="signIn">حساب دارید؟ وارد شوید</button>
          </div>
          <div class="overlay-panel overlay-right">
            <h1>!خوش آمدید</h1>
            <p>
              جهت ورود پنل کاربری کیک پیک لطفا از شماره تماس خود استفاده کنید
            </p>
            <button class="ghost" id="signUp">حساب ندارید؟ ثبت نام کنید</button>
          </div>
        </div>
      </div>
    </div>
        <script>
            const signUpButton = document.getElementById("signUp");
            const signInButton = document.getElementById("signIn");
            const container = document.getElementById("container");
            signUpButton.addEventListener("click", () => {container.classList.add("right-panel-active");});
            signInButton.addEventListener("click", () => {container.classList.remove("right-panel-active");});

        </script>
  </section>
{% endif %}
{% endblock %}

templates/accounts/password_required.html
{% extends 'base.html' %}
{%block TITLE%}Password required{%endblock%}
{% block content %}
<h1>Password required</h1>
<p>
You need a password to access this page.
{% if user.is_authenticated %}To proceed, please login with an account that has access.{% endif %}
</p>
<form action="{{ action_url }}" method="POST">
    {% csrf_token %}

    {{ form.non_field_errors }}

    <div>
        {{ form.password.errors }}
        {{ form.password.label_tag }}
        {{ form.password }}
    </div>

{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}
<input type="submit" value="Continue" />
</form>

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{%block TITLE%}ثبت نام کاربران{% endblock %}
{% block HEADING %}
<link rel="stylesheet" href="{% static 'css/accounts/stylelogin.css' %}" />
{% endblock %}
{% block CONTENT %}
{% if user.is_authenticated %}
<h3 style="color: red;"> Error : you are now Login ! </h3>
<button onclick="window.history.back();">Go Back</button>
<a href="{% url 'logout' %}"><button>logout</button></a>
{% else %}
    <div class="container-fluid">
      <div class="row">
        <div class="col asidelogform">
          <div class="container">
            <section class="main">
              <form class="form-3" method="POST">
                {% csrf_token %}
                <label for="{{ signup_form.phoneNumber.id_for_label }}">شماره تماس</label>
                {{ form.phoneNumber }}
                <label for="signup_form.password1.id_for_label">رمزعبور</label>
                {{ form.password1 }}
                <label for="signup_form.password2.id_for_label">تکرار رمزعبور</label>
                {{ form.password2 }}
                <input type="checkbox" name="remember" id="remember" />
                <label for="remember">مرا به خاطر بسپار</label>
                <input type="submit" name="submit" value="ساخت حساب کاربری" />
              </form>
            </section>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
{% endblock %}
